import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
 
const iransansFont = localFont({
    src: [
    {
      path: '../public/fonts/iransans/IRANSansWeb_Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/iransans/IRANSansWeb_Bold.woff2',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../public/fonts/iransans/IRANSansWeb_Light.woff2',
      weight: '100',
      style: 'normal',
    }
  ],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className="bg-gray-100">
      <body
        className={`${iransansFont.className} `}
      >
        {children}
      </body>
    </html>
  );
}
